### ISSUE TITLE
Duplicate entries for "bend"

### ISSUE THREAD

**Issue by khalid-hussain** [dolanskurd/Al-Mawrid#1]
There are duplicate entries for the word "bend". I don't have a physical copy to check if this is the case in the original book.

**Comment by 0xdolan** [comment]
Thanks for your note. You are right, actually I didn't modify the original texts, so the issue (if it counts as issue) is from the source text!

**Comment by khalid-hussain** [comment]
What are the links for the source text?

**Comment by 0xdolan** [comment]
APK
